server {
    listen 80;
    server_name localhost;

    # Клиентская часть (доступна на /)
    location / {
        root   /usr/share/nginx/html/client;
        index  index.html;
        try_files $uri $uri/ /index.html;
    }

    # Админка (доступна на /admin)
    location /admin {
        alias   /usr/share/nginx/html/admin;
        index  index.html;
        # Обрати внимание на путь в конце! Он должен указывать на index.html внутри админки
        try_files $uri $uri/ /admin/index.html;
    }

    # Кэширование статики
    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff2)$ {
        root /usr/share/nginx/html;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}